name: Gym App CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-apis:
    name: Run Postman API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Paystack QA Tests
        run: newman run tests/paystack_collection.json